# Generated by Django 4.1.2 on 2022-11-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0012_imagefields_remove_keywordpost_head_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finImg", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="Drawing",
            field=models.CharField(
                choices=[
                    ("Digital Art", "Digital Art"),
                    ("Impressionism", "Impressionism"),
                    ("Oil and Canvas", "Oil and Canvas"),
                    ("Sketched", "Sketched"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="Emotion",
            field=models.CharField(
                choices=[
                    ("Angry", "Angry"),
                    ("Depressed", "Depressed"),
                    ("Cheerful", "Cheerful"),
                    ("Neutral", "Neutral"),
                    ("Happy", "Happy"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="keywordpost",
            name="Weather",
            field=models.CharField(
                choices=[
                    ("Sunny", "Sunny"),
                    ("Rainy", "Rainy"),
                    ("Snowy", "Snowy"),
                    ("Cloudy", "Cloudy"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Drawing",
            field=models.CharField(
                choices=[
                    ("Digital Art", "Digital Art"),
                    ("Impressionism", "Impressionism"),
                    ("Oil and Canvas", "Oil and Canvas"),
                    ("Sketched", "Sketched"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Emotion",
            field=models.CharField(
                choices=[
                    ("Angry", "Angry"),
                    ("Depressed", "Depressed"),
                    ("Cheerful", "Cheerful"),
                    ("Neutral", "Neutral"),
                    ("Happy", "Happy"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="Weather",
            field=models.CharField(
                choices=[
                    ("Sunny", "Sunny"),
                    ("Rainy", "Rainy"),
                    ("Snowy", "Snowy"),
                    ("Cloudy", "Cloudy"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
